from __future__ import annotations


SHINY_CHARM_ITEM = "Shiny Charm"

BASE_SHINY_ODDS = 12000
SHINY_CHARM_ODDS = 8000
TM_DROP_ODDS = 1200
MEGA_STONE_DROP_ODDS = 6000
Z_CRYSTAL_DROP_ODDS = 4500
TERA_SHARD_DROP_ODDS = 350

TM_DROPS: tuple[str, ...] = (
    "TM001 - surf",
    "TM002 - stored-power",
    "TM003 - energy-ball",
    "TM004 - scald",
    "TM005 - ice-fang",
    "TM006 - tail-slap",
    "TM007 - light-screen",
    "TM008 - trailblaze",
    "TM009 - gunk-shot",
    "TM010 - vacuum-wave",
    "TM011 - rock-smash",
    "TM012 - venom-drench",
    "TM013 - power-gem",
    "TM014 - lunge",
    "TM015 - dragon-claw",
    "TM016 - drill-run",
    "TM017 - play-rough",
    "TM018 - stomping-tantrum",
    "TM019 - fire-blast",
    "TM020 - megahorn",
    "TM021 - will-o-wisp",
    "TM022 - earth-power",
    "TM023 - psybeam",
    "TM024 - magic-room",
    "TM025 - brutal-swing",
    "TM026 - shadow-claw",
    "TM027 - swords-dance",
    "TM028 - ice-beam",
    "TM029 - psych-up",
    "TM030 - calm-mind",
    "TM031 - flame-charge",
    "TM032 - psychic-terrain",
    "TM033 - outrage",
    "TM034 - bulk-up",
    "TM035 - earthquake",
    "TM036 - psychic-fangs",
    "TM037 - spikes",
    "TM038 - thunder-wave",
    "TM039 - confuse-ray",
    "TM040 - steel-wing",
    "TM041 - rock-tomb",
    "TM042 - round",
    "TM043 - giga-drain",
    "TM044 - acrobatics",
    "TM045 - phantom-force",
    "TM046 - coaching",
    "TM047 - low-sweep",
    "TM048 - charge-beam",
    "TM049 - psycho-cut",
    "TM050 - burning-jealousy",
    "TM051 - air-cutter",
    "TM052 - zen-headbutt",
    "TM053 - endeavor",
    "TM054 - icicle-spear",
    "TM055 - sandstorm",
    "TM056 - bulldoze",
    "TM057 - air-slash",
    "TM058 - focus-punch",
    "TM059 - bug-bite",
    "TM060 - bounce",
    "TM061 - leech-life",
    "TM062 - pay-day",
    "TM063 - metal-sound",
    "TM064 - screech",
    "TM065 - flamethrower",
    "TM066 - skitter-smack",
    "TM067 - hyper-voice",
    "TM068 - shadow-ball",
    "TM069 - stealth-rock",
    "TM070 - supercell-slam",
    "TM071 - expanding-force",
    "TM072 - revenge",
    "TM073 - imprison",
    "TM074 - sunny-day",
    "TM075 - low-kick",
    "TM076 - toxic",
    "TM077 - skill-swap",
    "TM078 - power-up-punch",
    "TM079 - poison-jab",
    "TM080 - body-press",
    "TM081 - grassy-glide",
    "TM082 - substitute",
    "TM083 - dragon-pulse",
    "TM084 - disarming-voice",
    "TM085 - retaliate",
    "TM086 - misty-explosion",
    "TM087 - fire-spin",
    "TM088 - ally-switch",
    "TM089 - rock-polish",
    "TM090 - snarl",
    "TM091 - leaf-storm",
    "TM092 - mega-kick",
    "TM093 - rock-blast",
    "TM094 - overheat",
    "TM095 - pluck",
    "TM096 - double-edge",
    "TM097 - attract",
    "TM098 - dragon-dance",
    "TM099 - giga-impact",
    "TM100 - foul-play",
    "TM101 - haze",
    "TM102 - baton-pass",
    "TM103 - heat-crash",
    "TM104 - dig",
    "TM105 - rock-slide",
    "TM106 - ice-spinner",
    "TM107 - flip-turn",
    "TM108 - seed-bomb",
    "TM109 - recycle",
    "TM110 - liquidation",
    "TM111 - speed-swap",
    "TM112 - brick-break",
    "TM113 - electro-ball",
    "TM114 - cross-poison",
    "TM115 - electric-terrain",
    "TM116 - defog",
    "TM117 - metronome",
    "TM118 - assurance",
    "TM119 - fire-fang",
    "TM120 - eerie-impulse",
    "TM121 - triple-axel",
    "TM122 - hex",
    "TM123 - rest",
    "TM124 - mud-shot",
    "TM125 - pain-split",
    "TM126 - safeguard",
    "TM127 - breaking-swipe",
    "TM128 - snowscape",
    "TM129 - psychic",
    "TM130 - trick-room",
    "TM131 - dream-eater",
    "TM132 - smart-strike",
    "TM133 - ice-punch",
    "TM134 - guard-swap",
    "TM135 - iron-head",
    "TM136 - solar-beam",
    "TM137 - hydro-pump",
    "TM138 - thunder-punch",
    "TM139 - reflect",
    "TM140 - false-swipe",
    "TM141 - taunt",
    "TM142 - shock-wave",
    "TM143 - rock-climb",
    "TM144 - solar-blade",
    "TM145 - mega-punch",
    "TM146 - amnesia",
    "TM147 - stone-edge",
    "TM148 - sleep-talk",
    "TM149 - grass-knot",
    "TM150 - work-up",
    "TM151 - venoshock",
    "TM152 - hurricane",
    "TM153 - future-sight",
    "TM154 - poltergeist",
    "TM155 - swagger",
    "TM156 - poison-tail",
    "TM157 - draining-kiss",
    "TM158 - focus-blast",
    "TM159 - crunch",
    "TM160 - close-combat",
    "TM161 - misty-terrain",
    "TM162 - brine",
    "TM163 - nasty-plot",
    "TM164 - high-horsepower",
    "TM165 - magical-leaf",
    "TM166 - petal-blizzard",
    "TM167 - torment",
    "TM168 - iron-tail",
    "TM169 - facade",
    "TM170 - cosmic-power",
    "TM171 - brave-bird",
    "TM172 - flare-blitz",
    "TM173 - wild-charge",
    "TM174 - temper-flare",
    "TM175 - alluring-voice",
    "TM176 - dragon-tail",
    "TM177 - dive",
    "TM178 - self-destruct",
    "TM179 - pounce",
    "TM180 - super-fang",
    "TM181 - endure",
    "TM182 - throat-chop",
    "TM183 - drain-punch",
    "TM184 - bullet-seed",
    "TM185 - gyro-ball",
    "TM186 - curse",
    "TM187 - aura-sphere",
    "TM188 - scorching-sands",
    "TM189 - dark-pulse",
    "TM190 - metal-claw",
    "TM191 - rain-dance",
    "TM192 - chilling-water",
    "TM193 - uproar",
    "TM194 - hyper-beam",
    "TM195 - roar",
    "TM196 - weather-ball",
    "TM197 - fly",
    "TM198 - agility",
    "TM199 - explosion",
    "TM200 - blizzard",
    "TM201 - night-shade",
    "TM202 - double-team",
    "TM203 - thunderbolt",
    "TM204 - tri-attack",
    "TM205 - sludge-bomb",
    "TM206 - dual-wingbeat",
    "TM207 - payback",
    "TM208 - mystical-fire",
    "TM209 - power-swap",
    "TM210 - wonder-room",
    "TM211 - u-turn",
    "TM212 - tera-blast",
    "TM213 - roost",
    "TM214 - thunder-fang",
    "TM215 - pollen-puff",
    "TM216 - whirlpool",
    "TM217 - water-pulse",
    "TM218 - pin-missile",
    "TM219 - razor-shell",
    "TM220 - darkest-lariat",
    "TM221 - power-whip",
    "TM222 - body-slam",
    "TM223 - smack-down",
    "TM224 - aerial-ace",
    "TM225 - muddy-water",
    "TM226 - waterfall",
    "TM227 - snore",
    "TM228 - volt-switch",
    "TM229 - icy-wind",
    "TM230 - x-scissor",
    "TM231 - fire-punch",
    "TM232 - thunder",
    "TM233 - electroweb",
    "TM234 - lash-out",
    "TM235 - super-fang",
    "TM236 - feather-dance",
    "TM237 - avalanche",
    "TM238 - flash-cannon",
    "TM239 - psyshock",
    "TM240 - heavy-slam",
    "TM241 - grassy-terrain",
    "TM242 - blaze-kick",
    "TM243 - protect",
    "TM244 - superpower",
    "TM245 - bug-buzz",
    "TM246 - scale-shot",
    "TM247 - dazzling-gleam",
    "TM248 - sludge-wave",
    "TM249 - meteor-beam",
)

MEGA_STONE_LOCATIONS: dict[str, tuple[str, ...]] = {
    "Abomasite": ("Kanto", "Hoenn", "Kalos", "Alola"),
    "Absolite": ("Kanto", "Hoenn", "Kalos", "Alola"),
    "Aerodactylite": ("Kanto", "Hoenn", "Kalos", "Alola"),
    "Aggronite": ("Hoenn", "Kalos", "Alola"),
    "Alakazite": ("Kanto", "Hoenn", "Kalos", "Alola"),
    "Altarianite": ("Hoenn", "Kalos", "Alola"),
    "Ampharosite": ("Hoenn", "Kalos", "Alola"),
    "Audinite": ("Hoenn", "Kalos", "Alola"),
    "Banettite": ("Hoenn", "Kalos", "Alola"),
    "Beedrillite": ("Kanto", "Hoenn", "Kalos", "Alola"),
    "Blastoisenite": ("Kanto", "Hoenn", "Kalos", "Alola"),
    "Blazikenite": ("Hoenn", "Kalos", "Alola"),
    "Cameruptite": ("Hoenn", "Kalos", "Alola"),
    "Charizardite X": ("Kanto", "Hoenn", "Kalos", "Alola"),
    "Charizardite Y": ("Kanto", "Hoenn", "Kalos", "Alola"),
    "Diancite": ("Hoenn", "Kalos", "Alola"),
    "Galladite": ("Hoenn", "Kalos", "Alola"),
    "Garchompite": ("Hoenn", "Kalos", "Alola"),
    "Gardevoirite": ("Hoenn", "Kalos", "Alola"),
    "Gengarite": ("Kanto", "Hoenn", "Kalos", "Alola"),
    "Glalitite": ("Hoenn", "Kalos", "Alola"),
    "Gyaradosite": ("Kanto", "Hoenn", "Kalos", "Alola"),
    "Houndoominite": ("Hoenn", "Kalos", "Alola"),
    "Kangaskhanite": ("Kanto", "Hoenn", "Kalos", "Alola"),
    "Latiasite": ("Hoenn", "Kalos", "Alola"),
    "Latiosite": ("Hoenn", "Kalos", "Alola"),
    "Lopunnite": ("Hoenn", "Kalos", "Alola"),
    "Lucarionite": ("Hoenn", "Kalos", "Alola"),
    "Medichamite": ("Hoenn", "Kalos", "Alola"),
    "Metagrossite": ("Hoenn", "Kalos", "Alola"),
    "Mewtwonite X": ("Kanto", "Kalos", "Alola"),
    "Mewtwonite Y": ("Kanto", "Kalos", "Alola"),
    "Pidgeotite": ("Kanto", "Hoenn", "Kalos", "Alola"),
    "Pinsirite": ("Kanto", "Hoenn", "Kalos", "Alola"),
    "Sablenite": ("Hoenn", "Kalos", "Alola"),
    "Salamencite": ("Hoenn", "Kalos", "Alola"),
    "Sceptilite": ("Hoenn", "Kalos", "Alola"),
    "Scizorite": ("Kanto", "Hoenn", "Kalos", "Alola"),
    "Sharpedonite": ("Hoenn", "Kalos", "Alola"),
    "Slowbronite": ("Kanto", "Hoenn", "Kalos", "Alola"),
    "Steelixite": ("Kanto", "Hoenn", "Kalos", "Alola"),
    "Swampertite": ("Hoenn", "Kalos", "Alola"),
    "Tyranitarite": ("Hoenn", "Kalos", "Alola"),
    "Venusaurite": ("Kanto", "Hoenn", "Kalos", "Alola"),
    "Barbaracite": ("Kalos",),
    "Chandelurite": ("Kalos",),
    "Chesnaughtite": ("Kalos",),
    "Chimechite": ("Alola",),
    "Clefablite": ("Kalos",),
    "Crabominite": ("Alola",),
    "Darkranite": ("Kalos",),
    "Delphoxite": ("Kalos",),
    "Dragalgite": ("Kalos",),
    "Dragoninite": ("Kalos",),
    "Drampanite": ("Kalos",),
    "Eelektrossite": ("Kalos",),
    "Emboarite": ("Kalos",),
    "Excadrite": ("Kalos",),
    "Falinksite": ("Kalos",),
    "Feraligite": ("Kalos",),
    "Floettite": ("Kalos",),
    "Froslassite": ("Kalos",),
    "Garchompite Z": ("Alola",),
    "Golurkite": ("Alola",),
    "Greninjite": ("Kalos",),
    "Hawluchanite": ("Kalos",),
    "Heatranite": ("Kalos",),
    "Lucarionite Z": ("Alola",),
    "Malamarite": ("Kalos",),
    "Meganiumite": ("Kalos",),
    "Meowsticite": ("Alola",),
    "Pyroarite": ("Kalos",),
    "Raichunite X": ("Alola",),
    "Raichunite Y": ("Alola",),
    "Scolipite": ("Kalos",),
    "Scraftinite": ("Kalos",),
    "Skarmorite": ("Kalos",),
    "Staraptite": ("Alola",),
    "Starminite": ("Kalos",),
    "Victreebelite": ("Kalos",),
    "Zeraorite": ("Kalos", "Alola"),
    "Zygardite": ("Kalos", "Alola"),
}

Z_CRYSTALS: tuple[str, ...] = (
    "Buginium Z",
    "Darkinium Z",
    "Dragonium Z",
    "Electrium Z",
    "Fairium Z",
    "Fightinium Z",
    "Firium Z",
    "Flyinium Z",
    "Ghostium Z",
    "Grassium Z",
    "Groundium Z",
    "Icium Z",
    "Normalium Z",
    "Poisonium Z",
    "Psychium Z",
    "Rockium Z",
    "Steelium Z",
    "Waterium Z",
    "Aloraichium Z",
    "Decidium Z",
    "Eevium Z",
    "Incinium Z",
    "Kommonium Z",
    "Lunalium Z",
    "Lycanium Z",
    "Marshadium Z",
    "Mewnium Z",
    "Mimikium Z",
    "Pikanium Z",
    "Pikashunium Z",
    "Primarium Z",
    "Snorlium Z",
    "Solganium Z",
    "Tapunium Z",
    "Ultranecrozium Z",
)

TERA_SHARDS: tuple[str, ...] = (
    "Normal Tera Shard",
    "Fire Tera Shard",
    "Water Tera Shard",
    "Electric Tera Shard",
    "Grass Tera Shard",
    "Ice Tera Shard",
    "Fighting Tera Shard",
    "Poison Tera Shard",
    "Ground Tera Shard",
    "Flying Tera Shard",
    "Psychic Tera Shard",
    "Bug Tera Shard",
    "Rock Tera Shard",
    "Ghost Tera Shard",
    "Dragon Tera Shard",
    "Dark Tera Shard",
    "Steel Tera Shard",
    "Fairy Tera Shard",
    "Stellar Tera Shard",
)


def region_key(value: str) -> str:
    return value.strip().lower()


def mega_stones_for_region(region_id: str) -> list[str]:
    target = region_key(region_id)
    return [
        stone
        for stone, regions in MEGA_STONE_LOCATIONS.items()
        if any(region_key(region) == target for region in regions)
    ]
